# Generated by Django 2.0.6 on 2018-07-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topping',
            name='stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
